{% set name = "firthmodels" %}
{% set version = "0.5.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firthmodels-{{ version }}.tar.gz
  sha256: b5e8ab5f694a2c26abef796f0cf26510a70e90e2a59b416799ca546118ae0b3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - scikit-learn >=1.6
    - scipy >=1.12

test:
  imports:
    - firthmodels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jzluo/firthmodels
  dev_url: https://github.com/jzluo/firthmodels
  summary: Firth-penalized models in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jzluo
