{% set name = "firthmodels" %}
{% set version = "0.7.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firthmodels-{{ version }}.tar.gz
  sha256: 28e9b06b2698a6ca14f217ab56d7af2e405744c657eeaa55db42e824ba5ae7fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - scikit-learn >=1.6
    - scipy >=1.12
    - typing-extensions >=4.15.0

test:
  imports:
    - firthmodels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jzluo/firthmodels
  dev_url: https://github.com/jzluo/firthmodels
  summary: Firth-penalized models in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jzluo
